[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --class=WordSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.2"