services:
  - type: web
    name: greek-georgian-dictionary
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      # Only seed if database is empty
      if [ $(php artisan tinker --execute="echo App\\Models\\Word::count();") -eq 0 ]; then
        echo "Database empty, seeding..."
        php artisan db:seed --force
      else
        echo "Database has data, skipping seeder"
      fi
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie