databases:
  - name: greek-georgian-dictionary-db
    plan: free

services:
  - type: web
    name: greek-georgian-dictionary
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: 
      - key: SESSION_SAME_SITE
        value: lax
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: greek-georgian-dictionary-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: greek-georgian-dictionary-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: greek-georgian-dictionary-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: greek-georgian-dictionary-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: greek-georgian-dictionary-db
          property: password